### ISSUE TITLE
How to add categories

### ISSUE THREAD

**Issue by Fanom2813** [tomatophp/filament-ecommerce#13]
Hello , i have just installed the plugin , however there is no option to add a new category or tag for product
see the screenshot below 

<img width="1338" alt="Screenshot 2024-10-10 at 11 02 40 AM" src="https://github.com/user-attachments/assets/eda06e1c-fc38-4f62-b174-069d926bc3f3">

did i miss something ? thank you

**Comment by 3x1io** [comment]
you need to allow [Filament CMS](https://github.com/tomatophp/filament-cms) to add and manage categories
