### ISSUE TITLE
Publishable resources?

### ISSUE THREAD

**Issue by magarrent** [tomatophp/filament-ecommerce#14]
Hey! First of all, great job with the package, really worth it

Is there a possibility to publish the filament resources? Most of the time, we need specific fields or to edit some of them. Any plans to do that?

Just asking, thanks!! 🙏

**Comment by 3x1io** [comment]
you can publish the full package using [Filament Plugins Manager](https://github.com/tomatophp/filament-plugins)

```bash
composer require tomatophp/filament-plugins
```

before use this feature please make sure that you are publish the config file of `modules.php` using this command

```bash
 php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --tag="config"
```

on the config file edit this `'enabled' => true,`

```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Scan Path
    |--------------------------------------------------------------------------
    |
    | Here you define which folder will be scanned. By default will scan vendor
    | directory. This is useful if you host the package in packagist website.
    |
    */
    'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/*/*'),
        ],
    ],
]
```

all of this plugin can work as a module inside your app using our `filament-plugins` package and use this command

```bash
php artisan filament-plugins:publish
```

and type the name of the plugin you went to publish, if you don't know the plugin name you can use the list of all plugins using this command

```bash
php artisan module:list
```
