### ISSUE TITLE
[Feature] Add multi-vendor[SaaS] support to Resources.

### ISSUE THREAD

**Issue by Wotan6891** [tomatophp/filament-ecommerce#4]
HI, FRIEND,

GREAT WHAT YOU DO IN FILAMENTPHP.

I HAVE THIS QUESTION:

ARE YOU GOING TO ADD MULTIVENDOR?

THANK YOU

**Comment by 3x1io** [comment]
I think it can work with multi-vendor just by setting a team_id on every table and user a Teams, and I think it will be great if I add this, so np we can schedule it.

**Comment by Wotan6891** [comment]
Great thanks

**Comment by bfiessinger** [comment]
+1 on this

**Comment by 3x1io** [comment]
ready Add multi-vendor (SaaS) and codes manager #10
