### ISSUE TITLE
Error on migrate fresh - BUG

### ISSUE THREAD

**Issue by SanthoshSivan-Dev** [tomatophp/filament-ecommerce#5]
Hi,

After running the command `php artisan filament-settings-hub:install`, I encountered an error during the migration process. I have attached the screenshot of the error below. I am using PostgreSQL as the database.

![image](https://github.com/user-attachments/assets/82ab266b-64ef-4da8-aa05-abc40cc4572d)

**Comment by 3x1io** [comment]
this error is on[ filament-location](https://www.github.com/tomatophp/filament-locations) plugin please move it

**Comment by SanthoshSivan-Dev** [comment]
@3x1io , Could I remove or move this?

**Comment by 3x1io** [comment]
as you like you can move or just leave it closed

**Comment by krognome** [comment]
> Hi,
> 
> After running the command `php artisan filament-settings-hub:install`, I encountered an error during the migration process. I have attached the screenshot of the error below. I am using PostgreSQL as the database.
> 
> ![image](https://github.com/user-attachments/assets/82ab266b-64ef-4da8-aa05-abc40cc4572d)

Hello does this package work well with Postgresql? I am considering using it but am unsure if it will work well with my Postgresql DB
