### ISSUE TITLE
Error while create order

### ISSUE THREAD

**Issue by SanthoshSivan-Dev** [tomatophp/filament-ecommerce#6]
Hi,

When I click "Create Order," an error occurs. I've attached a screenshot below. 

Can you help me figure out the issue?

![image](https://github.com/user-attachments/assets/09070897-591f-4dc8-9b63-50ab5a630cfd)

**Comment by abd1407** [comment]
Same issue

**Comment by megoxv** [comment]
install jetstream.
```bash
composer require laravel/jetstream
```

**Comment by 3x1io** [comment]
hi @abd1407 just remove `InteractWithTenant` trait from your Account Model
