### ISSUE TITLE
Missing category 

### ISSUE THREAD

**Issue by hany-cmd** [tomatophp/filament-ecommerce#9]
Should the category be added separately because it is not included in the plugin?

**Comment by hany-cmd** [comment]
> [TOT-85 Missing category](https://linear.app/tomatophp/issue/TOT-85/missing-category)

Thanks but what is this link?

**Comment by megoxv** [comment]
You can use the [filament-cms](https://github.com/tomatophp/filament-cms) package, as it includes a category feature

**Comment by 3x1io** [comment]
hi @hany-cmd this link is just for manage issues don't worry about it, for category as @megoxv you can use CMS plugin to manage your categories as it's a part of E-commerce system
